# Generated by Django 4.1.13 on 2024-02-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_username_stock_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='action',
            new_name='operations',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='price',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='volume',
            new_name='total_amount',
        ),
    ]
