# Generated by Django 4.1.13 on 2024-02-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_action_log_operations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='warning1',
            field=models.IntegerField(blank=0, default=0),
        ),
    ]
