# Generated by Django 4.1.13 on 2024-02-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_block_user_warning1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='warning1',
            new_name='warning',
        ),
    ]
