# Generated by Django 4.1.13 on 2024-02-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_warning1_user_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='warning',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
