# Generated by Django 4.1.13 on 2024-02-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_block_alter_user_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_balance',
            field=models.IntegerField(blank=True),
        ),
    ]
